version: "3.8"

services:
  db:
    image: postgres
    container_name: testappdb
    restart: always
    environment:
      - POSTGRES_DB=testappdb
      - POSTGRES_USER=testappuser
      - POSTGRES_PASSWORD=testapppass
    ports:
      - "5432:5432"
